### ISSUE TITLE
error in viamaris

### ISSUE THREAD

**Issue by jane-edgeloe** [pygmyperch/melfuR#5]
Hi Chris

I have tried to run viamaris to generate oceanographic distances between my sites using the following code

> latlon <- "C:/Users/21981245/Desktop/DaRT workshop/lat_lon_1.csv"
> latlon_data_1 <- read.csv(latlon)
> dist.mat <- viamaris(latlon_data_1, extent.buffer = 5)

I keep getting the following error....

preparing raster
Error in viamaris(latlon_data_1, extent.buffer = 5) : 
  object 'wkt' not found

Have attached my csv here for reference- I think the format looks ok?

Do you have any suggestions for the error?

[lat_lon_1.csv](https://github.com/pygmyperch/melfuR/files/15020042/lat_lon_1.csv)

**Comment by pygmyperch** [comment]
Hi Jane,

Thanks for opening the issue, this was a bug introduced in my last update to the function. If you uninstall melfuR and reinstall from GitHub it should all work now.

Let me know if you have any more problems.
Cheers,
Chris

**Comment by pygmyperch** [comment]
HiJane,

As I haven't heard anything more I am closing this issue now.
Please don't hesitate to let know if you have any more problems.

Cheers,
Chris
